mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
constant:
  SEND_URL: https://sms.yunpian.com/v2/sms/single_send.json
  API_KEY: c2b3ecaa39bb1ef293b45b603fb3ef41
  MODEL_REGISTER: 1
  MODEL_LOGIN: 2
  MODEL_CHANGE_PASS: 3
  TEXT_IDENTIFY: 【围博编程】您的验证码是#code#
  TEXT_LOGIN: 【围博编程】正在进行登录操作，您的验证码是#code#
  TEXT_CHANGE_PASS: 【围博编程】您正在修改用户密码,验证码为#code#,请勿泄漏给他人
  ip: www.foxluo.cn
